T11: Digital Root
Dakshita-Minocha/Training pull request #16
Opened 2023-08-21 08:38 UTC by Dakshita-Minocha

2023-08-23 09:09 UTC, v-priya requested changes

2023-08-24 05:36 UTC, Dakshita-Minocha commented on Program.cs
> +               while (i > 1) {
okay this works better for single digits also, thanks!

2023-08-29 13:26 UTC, v-priya requested changes

2023-08-29 13:26 UTC, v-priya commented on Program.cs
> +               if (input.All (c => Char.IsDigit (c) | c == '-')) break;
This 'or' condition will accept '-' char as input.

2023-08-30 03:29 UTC, Dakshita-Minocha commented on Program.cs
> +               if (input.All (c => Char.IsDigit (c) | c == '-')) break;
Yes I added that because I wanted it to accept negative numbers as well.

2023-08-30 03:41 UTC, v-priya commented on Program.cs
> +               if (input.All (c => Char.IsDigit (c) | c == '-')) break;
But, after accepting the input you are checking for numbers <= 0 which is contradictory.
```
if (num <= 0)
   Console.WriteLine ("\nError: Digital root is only defined for natural numbers. Try again.\n");
```

2023-08-30 05:23 UTC, v-priya approved these changes

2023-08-30 05:23 UTC, closed without merging