T12: Pascals triangle
Dakshita-Minocha/Training pull request #17
Opened 2023-08-21 10:19 UTC by Dakshita-Minocha

2023-08-23 08:50 UTC, v-priya requested changes
Fix the output alignment. The spacing should be evenly distributed.

2023-08-30 06:01 UTC, v-priya requested changes

2023-08-30 06:01 UTC, v-priya commented on Program.cs
> +                  switch (i) {
Can this not be simplified by checking `if (i > 0)`, eliminating the switch case?

2023-08-30 06:45 UTC, Dakshita-Minocha commented on Program.cs
> +                  switch (i) {
does it not end up being the same thing?

2023-08-30 07:01 UTC, v-priya commented on Program.cs
> +                  switch (i) {
Switch is more beneficial when there are multiple conditions. But in this case, it adds no value. `row1.Add (1);` is used both in `case 1` and also in `default`. For `case 0`, nothing is handled. So, why not just use `if (i > 0)`. This would also reduce the redundancy of `row1.Add (1);`

2023-08-31 05:04 UTC, v-priya approved these changes

2023-08-31 05:04 UTC, closed without merging