T17: String permutations
Dakshita-Minocha/Training pull request #22
Opened 2023-08-29 06:29 UTC by Dakshita-Minocha

2023-08-31 10:26 UTC, v-priya requested changes

2023-08-31 10:26 UTC, v-priya commented on Program.cs
> +            perm = Permutations (input.ToList (), perm, k, l);
Why `ToList ()`? Can simply be an array as they are indexable too. No specific advantage of using a list here

2023-08-31 10:26 UTC, v-priya commented on Program.cs
> +         if (perm.Count < NumofPermutations (len)) Permutations (input, perm, k, l);
This will compute the `NumofPermutations` as many times the loop iteration happens. Cache it.

2023-09-01 04:54 UTC, Dakshita-Minocha commented on Program.cs
> +            perm = Permutations (input.ToList (), perm, k, l);
I'm changing the value of the input in the function. Arrays aren't mutable right?

2023-09-01 05:10 UTC, v-priya commented on Program.cs
> +            perm = Permutations (input.ToList (), perm, k, l);
You cannot add elements to an array without resizing. So, size is immutable. But, the elements inside an array can be changed.

2023-09-01 09:38 UTC, v-priya approved these changes

2023-09-01 09:38 UTC, closed without merging