T26: Classes MyList<T>
Dakshita-Minocha/Training pull request #33
Opened 2023-10-04 12:12 UTC by Dakshita-Minocha

2023-10-25 10:28 UTC, meenashriTMM requested changes

2023-10-25 10:28 UTC, meenashriTMM commented on ClassSolution/MsTest/UnitTest1.cs
> +using Classlib;
namespace should be after all the using statements

2023-10-25 10:28 UTC, meenashriTMM commented on ClassSolution/MsTest/UnitTest1.cs
> +   MyList<int> myList = new ();
Stick to naming conventions

2023-10-25 10:28 UTC, meenashriTMM commented on ClassSolution/MsTest/UnitTest1.cs
> +   public void TestAdd () {
Check the behaviour of MyList<T> with that of built-in List<T>

2023-10-25 10:28 UTC, meenashriTMM commented on Training.csproj
> +    <Compile Remove="PClassLib\**" />
Why changes in Training.csproj? You havent modified anything here.

2023-10-25 10:28 UTC, meenashriTMM commented on Training.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Training", "Training.csproj", "{722E18D2-835C-475C-823A-79C9FFBCFE89}"
Why changes in Training.sln? You havent modified anything here.

2023-10-25 10:28 UTC, meenashriTMM commented on ClassSolution/Demo/Demo.csproj
> +	<OutDir>../bin/</OutDir>
Spacing is incorrect for all the *.csproj files.

2023-10-25 10:28 UTC, meenashriTMM commented on ClassSolution/Classlib/Class1.cs
> +// Class1.cs
Give meaningful file names

2023-10-25 10:28 UTC, meenashriTMM commented on Program.cs
> +﻿// ------------------------------------------------------------------------------------------------
Why change the Program.cs in Training project?

2023-10-25 10:30 UTC, meenashriTMM commented
.gitignore & .gitconfig is still part of the repository!

2023-10-26 08:40 UTC, Dakshita-Minocha commented on ClassSolution/Classlib/Class1.cs
> +using static System.Console;
I wrote this so I could use WriteLine() directly, should I not?

2023-10-26 08:42 UTC, meenashriTMM requested changes

2023-10-26 08:42 UTC, meenashriTMM commented on ClassSolution/Classlib/Class1.cs
> +using static System.Console;
But, you haven't used WriteLine in this file. Unless used, there is no use in including that using statement.

2023-10-26 08:45 UTC, Dakshita-Minocha commented on ClassSolution/Classlib/Class1.cs
> +      array = new T[Capacity];
But Clear doesn't resize right? just sets everything back to default value while keeping the size the same

2023-10-26 09:18 UTC, Dakshita-Minocha commented on ClassSolution/Classlib/Class1.cs
> +      CheckIndex (index);
Won't array[i] = array[i-1] just copy back the same value in the whole array?

2023-10-26 09:21 UTC, meenashriTMM commented on ClassSolution/Classlib/Class1.cs
> +      CheckIndex (index);
It won't if you iterate from the end
for (int i = Count; i > index; i--) mData[i] = mData[i - 1];

2023-10-26 09:26 UTC, Dakshita-Minocha commented on ClassSolution/Classlib/Class1.cs
> +      if (--Count <= Capacity / 2) Resize (0.5);
It gives null reference errors, dereferencing a null value and stuff like that

2023-10-26 09:31 UTC, meenashriTMM commented on ClassSolution/Classlib/Class1.cs
> +      if (--Count <= Capacity / 2) Resize (0.5);
Tried as below?

int idx = Array.IndexOf (array, a, 0, Count);
if (idx < 0) return false;
for (int i = idx; i < Count- 1; i++) array[i] = array[i + 1];
array[--Count] = default;
return true;

2023-10-26 10:54 UTC, Dakshita-Minocha commented on Training.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Training", "Training.csproj", "{722E18D2-835C-475C-823A-79C9FFBCFE89}"
I think I had some errors originally, so I had to remove and add references again. I think that's why it's showing as changes

2023-10-26 10:55 UTC, Dakshita-Minocha commented on Training.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Training", "Training.csproj", "{722E18D2-835C-475C-823A-79C9FFBCFE89}"
same with .csproj

2023-10-26 11:37 UTC, Dakshita-Minocha commented on ClassSolution/Classlib/Class1.cs
> +      if (--Count <= Capacity / 2) Resize (0.5);
yes

2023-10-27 15:22 UTC, meenashriTMM commented
.gitignore & .gitconfig is still part of the repository!
Also, make sure there are no changes in Training solution.

2023-11-01 07:32 UTC, meenashriTMM requested changes

2023-11-01 07:32 UTC, meenashriTMM commented on ClassSolution/Classlib/MyListT.cs
> +   public void RemoveAt (int index) => Remove (mArray[index]);
This would throw an exception if index is outside the bounds.
Using indexer would help as you're checking the index & then throwing the exception. 
public void RemoveAt (int index) => Remove (this[index]);

2023-11-01 07:32 UTC, meenashriTMM commented on ClassSolution/MsTest/TestMyListT.cs
> +      Assert.ThrowsException<IndexOutOfRangeException> (() => mMyList.Insert (10, 2));
I think this is a mistake from copy paste work of Insert test case

2023-11-01 10:05 UTC, meenashriTMM approved these changes

2023-11-01 10:05 UTC, closed without merging