T27: Stack<T>
Dakshita-Minocha/Training pull request #36
Opened 2023-10-09 12:42 UTC by Dakshita-Minocha

2023-10-27 15:18 UTC, meenashriTMM requested changes

2023-10-27 15:18 UTC, meenashriTMM commented on ClassSolution/Classlib/Classlib.csproj
> +	<OutDir>../bin/</OutDir>
Spacing is incorrect. Update it for all csproj files

2023-10-27 15:18 UTC, meenashriTMM commented on ClassSolution/Classlib/MyStack.cs
> +// MyStack.cs
Do not leave unnecessary spaces at end of statement. Update it for all cs files.

2023-10-27 15:18 UTC, meenashriTMM commented on Program.cs
>  // Copyright (c) Metamation India.
No need to change anything in Training solution.

2023-10-27 15:18 UTC, meenashriTMM commented on ClassSolution/MsTest/TestMyStack.cs
> +// ------------------------------------------------------------------------------------------------
Checked if the code coverage is 100%?

2023-11-01 04:33 UTC, Dakshita-Minocha commented on ClassSolution/MsTest/TestMyStack.cs
> +// ------------------------------------------------------------------------------------------------
yes, its 100%

2023-11-01 07:34 UTC, meenashriTMM approved these changes

2023-11-01 07:35 UTC, closed without merging