A8: Unary Operator
Dakshita-Minocha/Training pull request #39
Opened 2023-11-20 09:48 UTC by Dakshita-Minocha

2023-12-20 12:12 UTC, sdinesh-90 requested changes
I am reviewing a08.evaluator. In that 2-(3-(5) gives result as 4. I think it should raise error.
Also, please change test to use a08.evaluator.

2023-12-20 12:12 UTC, sdinesh-90 commented on TestTraining/TestTraining.cs
> +   };
Format the input

2023-12-22 05:26 UTC, sdinesh-90 requested changes
> (3 + 4)
7
> (3 + 4
Invalid Expression
> (3 + 4)
Invalid Expression
>
Third expression should return 7

> -sin45 + sin45
-1.4142135624
> a = -sin45
-0.7071067812
> b = sin 45
0.7071067812
> a + b
0
> -sin45 + sin45
-1.4142135624
>
-sin45 + sin45 should return 0

2023-12-22 07:17 UTC, Dakshita-Minocha commented on a08.evaluator/Token.cs
> +         '/' => a / b,
This is happening every time I format.

2023-12-22 07:19 UTC, Dakshita-Minocha commented on a08.evaluator/Tokenizer.cs
> +   public Token Next (List<Token> tokens) {
Need current list count also, should I pass that separately too?

2023-12-22 07:42 UTC, Dakshita-Minocha commented on a08.evaluator/Evaluator.cs
> +      } catch (Exception) { mOperators.Push (op); return; }
I've added another condition while calling this, I think it should work now.

2023-12-22 10:38 UTC, sdinesh-90 commented on a08.evaluator/Tokenizer.cs
> +   public Token Next (List<Token> tokens) {
Why you need count? If previous token is null you can consider the list to be empty.

2023-12-22 10:40 UTC, Dakshita-Minocha commented on a08.evaluator/Tokenizer.cs
> +   public Token Next (List<Token> tokens) {
Won't it throw an exception?

2023-12-22 10:43 UTC, sdinesh-90 commented on a08.evaluator/Tokenizer.cs
> +   public Token Next (List<Token> tokens) {
if (prevToken == null || prevToken is TOperator or TPunctuation { Punct: '(' })

So, I don't think there will be exception.

2023-12-22 10:45 UTC, sdinesh-90 commented on a08.evaluator/Token.cs
> +         '/' => a / b,
It is better to format selection instead of using format document. With experience you will be able to achieve spacing without using format selection or format document.

2023-12-22 11:00 UTC, Dakshita-Minocha commented on a08.evaluator/Tokenizer.cs
> +   public Token Next (List<Token> tokens) {
okay

2023-12-22 11:30 UTC, Dakshita-Minocha commented on a08.evaluator/Token.cs
> +         '/' => a / b,
Okay :)

2023-12-22 11:43 UTC, sdinesh-90 requested changes

2023-12-22 11:43 UTC, sdinesh-90 commented on a08.evaluator/Evaluator.cs
> +         } catch (Exception) { return; }
If you want to use try catch, you should not just return. It is better for application to crash instead of silently ignoring possible unexpected behavior. Also, you should log the exception. In our case, don't use try catch. Catch the exception at the main method.

2023-12-26 06:04 UTC, Dakshita-Minocha commented on a08.evaluator/Evaluator.cs
> +         } catch (Exception) { return; }
In this case it was proving useful for when there are too many operators and it throws a stack empty exception, I wanted it to simply return to the previous method and throw the relevant exception if its not handled. Should I throw it here itself?

2023-12-26 06:06 UTC, sdinesh-90 commented on a08.evaluator/Evaluator.cs
> +         } catch (Exception) { return; }
Then catch that specific exception and throw your own exception or other method to handle.

2023-12-26 06:12 UTC, Dakshita-Minocha commented on a08.evaluator/Evaluator.cs
> +         } catch (Exception) { return; }
Can I log it and return? or should I log it and rethrow?

2023-12-26 06:32 UTC, Dakshita-Minocha commented on a08.evaluator/Evaluator.cs
> +         } catch (Exception) { return; }
Also, should I just log just the system exceptions or should I log every exception that I'm throwing too?

2023-12-29 08:34 UTC, sdinesh-90 requested changes

2023-12-29 08:34 UTC, sdinesh-90 commented on a08.evaluator/Evaluator.cs
> +   }
Good you created your own exception class.
If I type as below and change the etc folder to etc2 (etc folder won't be available in all system)
> a +
Could not find a part of the path 'C:\etc2\LogFile.txt'.
>

If etc folder is missing, this will create issue. Also, we should not log while creating the exception. So, construct the exception. Log inside try catch of Program.Main method. Already, we are logging the information through console. So, you can skip it.

2023-12-29 08:34 UTC, sdinesh-90 commented on a08.evaluator/Evaluator.cs
> +         } catch (Exception) { throw new EvalException ("Too few operands"); }
You are using try catch to check whether you have only one operand. Simple method is to check whether mOperands.IsEmpty and then throw the exception. Another method is to catch specific exception as below:
```suggestion
         try {
            f2 = mOperands.Pop ();
         } catch (InvalidOperationException) { throw new EvalException ("Too few operands"); }

```
In the above case if stack is empty, it throws InvalidOperationException.

2023-12-29 08:34 UTC, sdinesh-90 commented on a08.evaluator/Evaluator.cs
> +         } catch (Exception) { throw new EvalException ("Too few operands"); }
In general, we have to code in such a way exceptions are rarely thrown. More details [here](https://www.joelonsoftware.com/2003/10/13/13/).

2023-12-29 10:48 UTC, sdinesh-90 approved these changes

2023-12-29 10:49 UTC, closed without merging