A10.1: File Parser - State Machine
Dakshita-Minocha/Training pull request #40
Opened 2023-11-21 12:04 UTC by Dakshita-Minocha

2023-11-27 06:40 UTC, sdinesh-90 requested changes

2023-11-27 06:40 UTC, sdinesh-90 commented on TestTraining/TestTraining.cs
> +// Training ~ DriveA training program for new joinees at Metamation, Batch- July 2023.
```suggestion
// Training ~ A training program for new joinees at Metamation, Batch- July 2023.

```

2023-11-27 06:40 UTC, sdinesh-90 commented on TestTraining/TestTraining.cs
> +// Training ~ DriveA training program for new joinees at Metamation, Batch- July 2023.
I think you replaced A with DriveA. There are other ways to rename a variable. I use Ctrl + . (Quick action) after renaming the variable. Arvind suggested Ctrl + R + R.

2023-11-27 06:40 UTC, sdinesh-90 commented on TestTraining/TestTraining.cs
> +      Dictionary<string, (string, string, string, string, string)> validPaths = new () {
Normally if you have five string to capture, it is better to use a Struct or assign name to each string for clarity. See [here](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-tuples).

2023-11-27 06:40 UTC, sdinesh-90 commented on Training/Program.cs
> +         WriteLine (Path.PathParse (path, out (string, string, string, string, string) ActOutput) + "\t" + ActOutput);
In our company, we use 3 spaces instead of tab \t. I think main reason is tab can be configured to have three or more spaces and it will appear different across developer machines.

2023-11-27 06:40 UTC, sdinesh-90 commented on Training/Program.cs
> +      //WriteLine (fp.FilePath);
Avoid including commented code.

2023-11-27 06:40 UTC, sdinesh-90 commented on TestTraining/TestTraining.cs
> +      Assert.AreEqual ("FileName: training.sln\nDrive: c\nDirectory: workgit\nFile Path: workgit/dakshita\n", path.ToString ());
In Windows, line ending is \r\n and in Unix based OS, it is \n. Environment.NewLine will have that information. This is just for your information.

2023-11-27 06:40 UTC, sdinesh-90 commented on Training/Program.cs
> +         }
else is not required.
```suggestion
         if (mComputed)
            return mFilePath;
            mValid = PathParse (mPath, out (string drive, string dir, string path, string filename, string ext) f);
            mFilePath = mValid ? f : ("", "", "", "", "");
            mComputed = true;
            nComputations++;
            return mFilePath;

```

2023-11-27 06:40 UTC, sdinesh-90 commented on Training/Program.cs
> +         }
Better way is as follows:
```suggestion
        if (mFilePath.drive == null) { 
           mValid = PathParse (mPath, out (string drive, string dir, string path, string filename, string ext) f);
            mFilePath = mValid ? f : ("", "", "", "", "");
            mComputed = true;
            nComputations++;
        }       
            return mFilePath;

```
Above code avoids two return mFilePath, mComputed variable as drive should not be null even if is not valid.

2023-11-27 06:40 UTC, sdinesh-90 commented on Training/Program.cs
> +   (string drive, string dir, string path, string filename, string ext) mFilePath;
We can use capital starting letter for variable.

2023-11-27 06:40 UTC, sdinesh-90 commented on Training/Program.cs
> +            nComputations++;
This is same as FilePath implementation. If there are two such identical implementation, we have to move it to common method and call that. Reason is if you change in one place you have to remember to change in another place also.

2023-11-27 06:40 UTC, sdinesh-90 commented on Training/Program.cs
> +            return mValid;
Below code is how we normally implement lazy evaluation where the code used to compute multiple vaiable is shared. In this case, Computing FilePath also compute valid state.
```suggestion
        _ = FilePath;
        return mValid;

```

2023-11-27 06:40 UTC, sdinesh-90 commented on Training/Program.cs
> +   public int nComputations { get; private set; }
Property name should start with Capital letter.

2023-11-27 06:40 UTC, sdinesh-90 commented on Training/Program.cs
> +enum EState { DriveA, DriveB, DriveC, DirA, PathA, FileA, End, Err };
As it is not used anywhere declare it inside Path class

2023-11-27 06:40 UTC, sdinesh-90 commented on Training/Program.cs
> +      return false;
```suggestion
      if (s != End) return false;
        path = string.Join ("", path.Replace ("\\", "/").Skip (1));
        string[] parts = path.Split ('/');
        fileName = parts[^1] + ext;
        path = dir + '/' + string.Join ("/", parts.SkipLast (1));
        filePath = (drive, dir, path, fileName, ext);
        return true;

```

2023-11-27 06:40 UTC, sdinesh-90 commented on Training/Program.cs
> +      filePath = ("", "", "", "", "");
This is not required. Before returning from the method compose filePath with path, dir ,drive, fileName and ext. As all are initialized to empty string, it will work.

2023-11-27 06:40 UTC, sdinesh-90 commented on Training/Program.cs
> +public class Path {
Name Path seems to be wrong. What you are doing is parsing the given string and extract the path. So, I think it is better to call it PathParser.

2023-11-27 06:40 UTC, sdinesh-90 commented on Training/Program.cs
> +public class Path {
Also, we already have two Path System.IO.Path and System.Windows.Shapes.Path,.

2023-11-27 09:50 UTC, Dakshita-Minocha commented on Training/Program.cs
> +public class Path {
I thought I'd call the class path, as I'm also making it such that we can make a path instance of it and use the filepath property

2023-11-27 09:51 UTC, Dakshita-Minocha commented on TestTraining/TestTraining.cs
> +      Assert.AreEqual ("FileName: training.sln\nDrive: c\nDirectory: workgit\nFile Path: workgit/dakshita\n", path.ToString ());
is it better to set a global alias for environment.newline for each program and use that instead?

2023-11-27 09:54 UTC, sdinesh-90 commented on TestTraining/TestTraining.cs
> +      Assert.AreEqual ("FileName: training.sln\nDrive: c\nDirectory: workgit\nFile Path: workgit/dakshita\n", path.ToString ());
You can do that.

2023-11-27 10:05 UTC, Dakshita-Minocha commented on Training/Program.cs
> +enum EState { DriveA, DriveB, DriveC, DirA, PathA, FileA, End, Err };
what region does this come under?

2023-11-27 10:06 UTC, sdinesh-90 commented on Training/Program.cs
> +enum EState { DriveA, DriveB, DriveC, DirA, PathA, FileA, End, Err };
It is similar to class #region enum .....

2023-11-27 10:22 UTC, Dakshita-Minocha commented on Training/Program.cs
> +enum EState { DriveA, DriveB, DriveC, DirA, PathA, FileA, End, Err };
Also, if I move it inside Path, I'm unable to use "using static EState". Is there some other way to do this?

2023-11-27 10:46 UTC, sdinesh-90 commented on Training/Program.cs
> +enum EState { DriveA, DriveB, DriveC, DirA, PathA, FileA, End, Err };
I think you have to use using static Path.EState as now enum becomes a nested type you have to mention Parent class name.

2023-11-28 09:46 UTC, Dakshita-Minocha commented on Training/Program.cs
> +         }
But what if the input start with something like '@' or some other non-alphabet?

2023-11-28 10:16 UTC, Dakshita-Minocha commented on TestTraining/TestTraining.cs
> +      Dictionary<string, (string, string, string, string, string)> validPaths = new () {
If I use a Struct, my test cases fail as the return type doesn't match. How do I deal with this?

2023-11-28 10:55 UTC, sdinesh-90 commented on TestTraining/TestTraining.cs
> +      Dictionary<string, (string, string, string, string, string)> validPaths = new () {
You can change the test case to use that struct.

2023-11-28 12:48 UTC, sdinesh-90 requested changes

2023-11-28 12:48 UTC, sdinesh-90 commented on Training/Program.cs
> +   bool mComputed = false;
We can achieve lazy evaluation without mComputed. You can use mFilePath.Drive. If it is null, the values are not computed. In Compute method, you are setting Drive to empty string if it is not valid, or to root drive if it is valid.

2023-12-01 07:11 UTC, sdinesh-90 requested changes

2023-12-01 07:11 UTC, sdinesh-90 commented on TestTraining/TestTraining.cs
> +   }
I thought of using struct with five fields/properties. Not struct for ValueTuple. ValuTuple is already a struct. I think you are using names for Items. In that case, you can ignore the struct. Main reason for changing from ValueTuple to Stuct is naming each field/property

2023-12-01 07:11 UTC, sdinesh-90 commented on Training/Program.cs
> +   internal int Computations { get; private set; }
Good that you decided to test your computation count.

2023-12-01 13:24 UTC, sdinesh-90 commented on TestTraining/TestTraining.cs
> +   }
Yes. For constructor also, you can use five variable instead of one value tuple.

2023-12-05 08:56 UTC, Dakshita-Minocha commented on TestTraining/TestTraining.cs
> +   }
like this? or did you mean in the PathParse class?

<img width="475" alt="image" src="https://github.com/Dakshita-Minocha/Training/assets/140157822/e76af2b7-4d3c-4755-96c8-1eb287c39055">

2023-12-08 08:43 UTC, sdinesh-90 commented on TestTraining/TestTraining.cs
> +   }
```suggestion
   struct Path {
      (string, string, string, string, string) filePath;
      public Path (string drive, string dir, string path, string filename, string ext) =>
         filePath = (drive, dir, path, filename, ext);
   }

```

2023-12-08 08:45 UTC, sdinesh-90 commented on TestTraining/TestTraining.cs
> +   }
This is better.
```suggestion
   struct Path {
      .. Individual property
      public Path (string drive, string dir, string path, string filename, string ext) =>
         (Drive, Directory, FilePath, FileName, Extension)= (drive, dir, path, filename, ext);
   }

```

2023-12-20 11:19 UTC, sdinesh-90 approved these changes

2023-12-20 11:19 UTC, closed without merging