A10.2: Double Ended Queue
Dakshita-Minocha/Training pull request #41
Opened 2023-11-23 12:25 UTC by Dakshita-Minocha

2023-11-23 14:57 UTC, sdinesh-90 requested changes

2023-11-23 14:57 UTC, sdinesh-90 commented on Training/Program.cs
> +   public int Capacity { get; private set; } = 4;
Add comments to public property.

2023-11-23 14:57 UTC, sdinesh-90 commented on Training/Program.cs
> +      return ele;
```suggestion
      Count--;
      return mArray[mEnd];

```

2023-11-23 14:57 UTC, sdinesh-90 commented on Training/Program.cs
> +      mEnd = mEnd == 0 ? Capacity - 1 : (mEnd - 1) % Capacity;
We can achieve this without using branch condition. Similar to how you increment by 1 circularly, you can also decrement by 1 circularly without using ternary operator or if condition.

2023-11-23 14:57 UTC, sdinesh-90 commented on Training/Program.cs
> +      return s;
Think before you using string concatenation. If mArray contains large number of elements, from 0 to Count -1 you will create Count number of string object and use only last string. Use StringBuilder, or String.Join

2023-11-23 14:57 UTC, sdinesh-90 commented on Training/Program.cs
> +   void Resize (double n) {
You are not using double n. You can remove it and modify the comments.

2023-11-23 14:57 UTC, sdinesh-90 commented on Training/Program.cs
> +      //
Add comments or remove //

2023-11-23 14:57 UTC, sdinesh-90 commented on Training/Program.cs
> +      mEnd = Capacity - Capacity / 4;
Instead of copying the content from 1/4 to 3/4, you could copy to 0 to 1/2 and the implementation will be simpler.

2023-11-23 14:57 UTC, sdinesh-90 commented on Training/Program.cs
> +      //WriteLine ($"Count: {q.Count}");
Don't commit comments unless it is debug code. Debug code should have last used date in the comments. As you have tests to validate, I think this can be removed.

2023-11-23 14:57 UTC, sdinesh-90 commented on TestTraining/TestTraining.cs
> +      }
Test should have Assert. WriteLine is for you reference. Use Assert to check whether array grows as expected, enqueue and dequeue only front and check. Then enqueue and dequeue only back and check. Then do both and check.

2023-11-24 04:27 UTC, Dakshita-Minocha commented on Training/Program.cs
> +      mEnd = Capacity - Capacity / 4;
The reason I did this was to accommodate FrontEnqueue as an O(1) operation. Otherwise, I'd have to resize the array every time I FrontEnqueue. It seemed okay to place it in the middle and grow the queue only when I needed to?

2023-11-24 12:54 UTC, closed without merging