A12: Wordle
Dakshita-Minocha/Training pull request #43
Opened 2023-12-08 11:25 UTC by Dakshita-Minocha

2023-12-12 12:57 UTC, asfar-nazar requested changes

2023-12-12 12:57 UTC, asfar-nazar commented on Training/Program.cs
> +   bool? CompareAndPrint (char[] input) {
input can be a string itself as it is an IEnumerable<char>

2023-12-12 12:57 UTC, asfar-nazar commented on Training/Program.cs
> +   static string[] mPuzzleWords, mDict;
```suggestion
   static string[] mPuzzleWords, mDictionaryWords;
```
For clarity

2023-12-12 12:57 UTC, asfar-nazar commented on Training/Program.cs
> +      if (!mDict.Any (x => x.SequenceEqual (string.Join ("", input)))) {
```suggestion
      if (!mDict.Contains (string.Join ("", input))) {
```

2023-12-12 12:57 UTC, asfar-nazar commented on Training/Program.cs
> +      if (input.SequenceEqual (mSecretWord)) return true;
```suggestion
      return input == mSecretWord;
```

2023-12-12 12:57 UTC, asfar-nazar commented on Training/Program.cs
> +      return false;
```suggestion

```

2023-12-12 12:57 UTC, asfar-nazar commented on Training/Program.cs
> +   bool? mCorrectGuess;
We can use a normal bool here. In GetInput method, we can remove the check for null as mCursor <= 5 performs the same check ie user is still typing a guess and has not hit enter

2023-12-12 12:57 UTC, asfar-nazar commented on Training/Program.cs
> +      (int c, int r) = (mCurrentCol, mRow);
Is the swap to temp variables necessary here ? We can just call ShiftTo (mStartCol - mMaxWordLen, mAlphaRow)

2023-12-12 12:57 UTC, asfar-nazar commented on Training/Program.cs
> +         mState[input[i]] = ForegroundColor = input[i] == mSecretWord[i] ? ConsoleColor.Green :
```suggestion
         if (input[i] == mSecretWord[i]) mState[input[i]] = ForegroundColor = ConsoleColor.Green;
         else if (mSecretWord.Contains (input[i])) {
            if (input[..i].Count (input[i]) >= mSecretWord.Count (input[i])) mState[input[i]] = ForegroundColor = ConsoleColor.DarkGray;
            else mState[input[i]] = ForegroundColor = ConsoleColor.Blue;
         } else mState[input[i]] = ForegroundColor = ConsoleColor.DarkGray;
```
To print only the first 'p' in blue if secret word is 'tempt' and input is 'apple'

2023-12-13 09:04 UTC, Dakshita-Minocha commented on Training/Program.cs
> +      if (!mDict.Any (x => x.SequenceEqual (string.Join ("", input)))) {
I thought I'd use any as it'd exit as soon as it got something that matched?

2023-12-13 09:35 UTC, asfar-nazar commented on Training/Program.cs
> +      if (!mDict.Any (x => x.SequenceEqual (string.Join ("", input)))) {
> I thought I'd use any as it'd exit as soon as it got something that matched?

Both 'Any' and 'Contains' will exit as soon as any of the elements match

2023-12-13 10:48 UTC, Dakshita-Minocha commented on Training/Program.cs
> +      (int c, int r) = (mCurrentCol, mRow);
Need to update value of currentCol and Row before and after use of PrintAlphabets(), these values are being used in NextLine() so it messes up the printing

2023-12-27 09:26 UTC, asfar-nazar commented on TestTraining/TestTraining.cs
> +         Assert.AreEqual (win, testLines[1]);
This is not needed as the entire file is compared in the previous line

2023-12-27 09:27 UTC, asfar-nazar requested changes
See comment

2024-01-02 07:27 UTC, asfar-nazar approved these changes

2024-01-02 07:27 UTC, closed without merging